name: webhook

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: trigger cloudflare deployment
        run: curl -X POST "${{secrets.CF_DEPLOY_URL}}"
