name: webhook

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: trigger cloudflare deployment
        run: curl -X POST "${{secrets.CF_DEPLOY_URL}}"

      - name: Trigger wcw-blog github pages workflow
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PAT_TOKEN_FOR_BLOG }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/asd55667/wcw-blog/dispatches \
          -d '{"event_type":"trigger_action","client_payload":{"unit":false,"integration":true}}'

